name: Michael Herbert-Gray
favicon: null
layout_spectrum: 0.3917035302147269
typography_spectrum: 0.5917046698741615
title: Mr. Michael Herbert-Gray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
