name: Michael Herbert-Gray
favicon: null
layout_spectrum: 0.3917035302147269
typography_spectrum: 0.5917046698741615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0617488210555166
  lightness: 0.28629920701496303
  saturation: 0.31033522821962833
  rhythmicContrast: 0.7993409677874297
purpose: []
